### PR TITLE
feat: add debian packaging

### PR DESCRIPTION
**Pull request by drlkf**
There is a lot to unpack in this pull request, so I'll try to make a comprehensive list of what was done:

1. converted the project to a **pyproject** structure
a. created a symlink named `theme` to avoid breaking the previous resource directory structure
2. removed the vendored `pyglet` version, and added the `pyproject.toml` file with the correct dependency to `pyglet`
a. the declared dependency is on the version that was vendored (`2.0.5`) or higher
b. current latest is `2.0.16` which seems to work fine, however no guarantees that `pyglet` won't break their APIs in future majors, so be on the lookout
3. changed the launcher scripts to auto-install dependencies in a virtualenv
4. refactored the `fightstick_hb` script to avoid copy-pasting the same logic in two separate scripts, when it's really only an inner script that differs
a. the regular `fightstick` calls the `hb` version if any parameter is provided, otherwise it calls the regular lever version
b. the `fightstick_hb` script now just calls the regular `fightstick` script with one parameter
5. added debian packaging using `dh-virtualenv`, that will vendor dependencies inside the package at build-time
a. current debian/ubuntu LTS are one major version behind on `pyglet`, hence vendoring instead of relying on system packages

The `README` should contain all the information needed for a current user to use the newer installation methods, but feel free to point out anything that is missing or not clear enough

cheers

### CODE REVIEW

**Comment by calexil** [comment]
in the middle of my work day rn, I'll review this soon. thank you for your hard work I had .deb and .exe on my todo list for the project and you single handedly crossed one off, you're awesome @drlkf

**Comment by drlkf** [comment]
i'm in no rush at all, take the time you need :o)

**Comment by calexil** [comment]
if I may ask, from a cursory review all this does is install the program to usr/bin instead of the user cloning the repo to their home directory. I don't really see how that's much of an improvement from how it is currently setup to be used.

Care to elaborate?

**Comment by drlkf** [comment]
there are two methods:
1. the launcher scripts install the dependencies in a virtualenv and generates an executable in the `PATH` for each board type
2. launching the python scripts manually is still possible, but you'd have to install the dependencies (i.e `pyglet`) yourself

the main goal of moving to this structure is to enable different packaging tools, i tried to keep a backward-compatible user experience with the launcher scripts, but ideally it would be preferrable to create python/debian packages or `.exe` for windows

**Comment by calexil** [comment]
While I truly appreciate your work here I am going to have to unfortunately close this pr for a few reasons:

1: Moving the structure really has no benefit imho, and in fact will make it more difficult for novice users to locate the program files for editing and troubleshooting.

2: Setting pyglet as a dependency rather than calling the specific version is a dangerous game, @benmoran56 frequently updates pyglet and has to intermittently manually review how it effects my code before sending version update pr's that don't break it.

3: When I said I planned to make a .deb version of the program what I meant was one that would *install* the program for the user and put in their applications menu, and that that .deb would be maintained by me in a ppa(which I still plan to do eventually)

Again thank you for your work here, I appreciate the effort and if your version works better for you then that's great!

-Cal

**Comment by drlkf** [comment]
no problem, i'll build my own version from a fork then

cheers

**Comment by calexil** [comment]
I will likely use this pr in the future for the basis of the ppa version, and if I do I will add you to the list of contributors! :)

**Pull request closed without merging**
