### PR TITLE
Automatic controller mapping edition

### PR DESCRIPTION
**Pull request by benmoran56**
I upgraded the included pyglet library to a version which has experimental SDL2-style automatic controller mapping. This means that instead of using a pyglet.input.Joystick device, you use a pyglet.input.GameController device. Just like SDL2 does it, this device is automatically mapped to a "virtual X360" layout. This means that Xbox 360, DS3, DS4, etc. will all work the same without the need for additional mappings. 

I didn't change any of the existing code, but just updated pyglet and added a new "fightstick.py" file, that *should* work universally on all sticks. You'll have to do a final tweak to get the buttons right, but it will remove the need for seperate versions of the program.

### CODE REVIEW

**Comment by calexil** [comment]
I am extremely hesitant to merge this, as I spent hours trying to get my qanba q1 mapped correctly starting here:

https://github.com/calexil/FightstickDisplay/blob/master/fightstick360.py#L29

**Comment by calexil** [comment]
this part was very difficult to sort out:

https://github.com/calexil/FightstickDisplay/blob/master/fightstick360.py#L86

**Comment by calexil** [comment]
the end goal here is to have it ask for an initial configuration, and store it in a file. which will totally avoid the need to edit the code

**Comment by calexil** [comment]
You know what, it looks like you didn't touch the launchers(360.py, ps4.py) that work already, so I'm gonna merge this.

**Comment by benmoran56** [comment]
Totally understand your hesitation. My goal too is to avoid any kind of configuration requirements. The GameController class does just that very thing. There are about 50+ built-in mappings for common controllers (taken from SDL2). We can also easily drop in community mapping lists, like this:
https://github.com/gabomdq/SDL_GameControllerDB
Just drop that into the folder, add one line of code to load it in, and all of those with "just work" as well.

The only thing I'm not sure about was whether the rz and z axis were the right stick, or the triggers. It should be very easy to tweak the code to compete it. The simplest way would be to put a few print statements under the input events, and see which ones are triggered. For example:  "print(stick, xvalue, yvalue)" under the "on_axis_motion" events, and "print(trigger, value)" under the "on_trigger_motion" event.

**Pull request merged**
