### PR TITLE
Refactor to better handle no-stick situations.

### LINKED ISSUE #11: Handle no gamepad situations more elegantly
ttd

### PR DESCRIPTION
**Pull request by benmoran56**
This fixes #11.
It's a bit of a refactor, but It should be cleaner now.

### CODE REVIEW

**Comment by benmoran56** [comment]
I don't know what the heck CodeFactor is talking about. It seems to have a ton of false alarms. The most obvious problem is that it doesn't understand how to inspect the event decorators. I realize their Python support is in beta, but it's pretty bad.  It also claims that all globals are bad, but the usage of globals in this tiny single file program are perfectly fine. It would make no sense to further convolute the code just to say "no globals". We could, but It would be silly.

**Comment by calexil** [comment]
going live for code review and merge

twitch.tv/calexil

9pm edt

**Comment by calexil** [comment]
also, you can just tell it to ignore stuff

**Comment by calexil** [comment]
Had to fix a couple small issues, like the sys import being unnecessary

and the lt/rt button layout being swapped

but everything is lookin good now

**Comment by calexil** [comment]
it cant tell when a variable is *going to* be used, just if it is currently

so it complains, you can just ignore it

**Comment by benmoran56** [comment]
Great!

**Comment by calexil** [comment]
I use codefactor so when I make changes, if I made a super rookie mistake, it tells me, and I can revert it.

https://stackoverflow.com/questions/12309269/how-do-i-write-json-data-to-a-file-in-python

We are gonna probably need another scene for the configurator, that fires when the remap buttons is hit

it should then go thru each button and flash the appropriate sprite to create a value that we float in a data set, and then dump to the layout file...

I think?...

**Comment by calexil** [comment]
you can add me on telegram or catch me on irc for faster communication btw

https://t.me/calexil

irc://irc.spotchat.org/linuxmint-help

username calexil

**Pull request merged**
